#pragma once

#include <gst/gst.h>

#if __has_include(<simaai/gstsimaaiallocator_common.h>)
#include <simaai/gstsimaaiallocator_common.h>
#define SIMA_HAS_SIMAAI_ALLOCATOR_COMMON 1
#else
#define SIMA_HAS_SIMAAI_ALLOCATOR_COMMON 0

#ifndef GST_SIMAAI_MEMORY_TARGET_GENERIC
#define GST_SIMAAI_MEMORY_TARGET_GENERIC (GST_MEMORY_FLAG_LAST << 0)
#define GST_SIMAAI_MEMORY_TARGET_OCM (GST_MEMORY_FLAG_LAST << 1)
#define GST_SIMAAI_MEMORY_TARGET_DMS0 (GST_MEMORY_FLAG_LAST << 2)
#define GST_SIMAAI_MEMORY_TARGET_DMS1 (GST_MEMORY_FLAG_LAST << 3)
#define GST_SIMAAI_MEMORY_TARGET_DMS2 (GST_MEMORY_FLAG_LAST << 4)
#define GST_SIMAAI_MEMORY_TARGET_DMS3 (GST_MEMORY_FLAG_LAST << 5)
#define GST_SIMAAI_MEMORY_TARGET_EV74 (GST_MEMORY_FLAG_LAST << 6)
#define GST_SIMAAI_MEMORY_FLAG_CACHED (GST_MEMORY_FLAG_LAST << 7)
#define GST_SIMAAI_MEMORY_FLAG_RDONLY (GST_MEMORY_FLAG_LAST << 8)
#define GST_SIMAAI_MEMORY_FLAG_DEFAULT (GST_MEMORY_FLAG_LAST << 9)
#endif

#endif
